Listen 8778

<VirtualHost *:8778>
    WSGIDaemonProcess placement-api processes=3 threads=1 user=placement group=placement display-name=%{GROUP}
    WSGIProcessGroup placement-api
    WSGIScriptAlias / /usr/bin/placement-api
    WSGIApplicationGroup %{GLOBAL}
    WSGIPassAuthorization On

    <Directory /usr/bin>
        <Files placement-api>
            Require all granted
        </Files>
    </Directory>

    ErrorLog /var/log/placement/placement-api.log
    CustomLog /var/log/placement/placement-api-access.log combined
</VirtualHost>

Alias /placement-api /usr/bin/placement-api
<Location /placement-api>
  SetHandler wsgi-script
  Options +ExecCGI
  WSGIProcessGroup placement-api
  WSGIApplicationGroup %{GLOBAL}
  WSGIPassAuthorization On
</Location>
